### PR TITLE
Add individual test reports and errors

### PR DESCRIPTION
**Pull request by seanson**
This adds individual test and reporting functionality similar to the
given output of pytest-html. As there is no support for collapsing
columns together in Markdown implementations we drop down to bare HTML
so we can use `colspan=3` and make the inline table output for test
results a lot cleaner at the expense of .md readability.

Issue: https://github.com/hackebrot/pytest-md/issues/7

### CODE REVIEW

**Comment by hackebrot** [comment]
Hi @seanson! 👋 

Thank you for submitting this PR. It is much appreciated! I just added a [CONTRIBUTORS.md][contributors] file and put down your name and also updated the [community section][community] on the README. 🙇

[community]: https://github.com/hackebrot/pytest-md/blob/master/README.md#community
[contributors]: https://github.com/hackebrot/pytest-md/blob/master/CONTRIBUTORS.md

I feel bad for saying this, but let's take a step back and discuss how we can present individual test results in the Markdown report. We don't necessarily have to adopt the format of [pytest-html][pytest-html] and use tables for that. We could use headings for test files and sub headings for individual test failures for example? 🤔

What do you think?

[pytest-html]: https://github.com/pytest-dev/pytest-html

**Comment by seanson** [comment]
Thanks for the credit! It's definitely a good consideration.

I've played around with the formatting to go for just Markdown in the way suggested. Is this the format you were aiming for?

# Test Report

*Report generated on 13-Mar-2019 at 23:49:44 by [pytest-md]*

[pytest-md]: https://github.com/hackebrot/pytest-md

## Summary

3 tests ran in 0.09 seconds

- 2 failed
- 1 passed


## Results

### tests/test_1.py

#### test_exception: Failed (0.00s)
```
def test_exception():
>       raise Exception("Failure\nmulti\nline")
E       Exception: Failure
E       multi
E       line

tests/test_1.py:6: Exception
```
#### test_pass: Passed (0.00s)

### tests/test_2.py

#### test_second_fail: Failed (0.00s)
```
def test_second_fail():
>       assert "foo" == "bar"
E       AssertionError: assert 'foo' == 'bar'
E         - foo
E         + bar

tests/test_2.py:2: AssertionError
```

**Comment by hackebrot** [comment]
I suggest grouping the individual results by outcome. The pytest CLI report shows errors first, then failures and after that I think we can use the ordering from before. We can also change the order in the summary accordingly, so it's more consistent:
- error
- failed
- passed
- skipped
- xfail
- xpass

Here's an example report (taken from the README)

---

# Test Report

*Report generated on 13-Mar-2019 at 15:16:17 by [pytest-md]* 📝

[pytest-md]: https://github.com/hackebrot/pytest-md

## Summary

12 tests ran in 0.10 seconds ⏱

- 2 error 😡
- 1 failed 😰
- 3 passed 😃
- 2 skipped 🙄
- 2 xfail 😞
- 2 xpass 😲

## 2 error 😡

### test_example1.py

0.02 s ⏱ ``ERROR at setup of test_error``

```text
    @pytest.fixture
    def number():
>       return 1234 / 0
E       ZeroDivisionError: division by zero

test_example1.py:34: ZeroDivisionError
```

### test_example2.py

0.02 s ⏱ ``ERROR at setup of test_nope``

```text
    @pytest.fixture
    def number():
>       return 1234 / 0
E       ZeroDivisionError: division by zero

test_example2.py:23: ZeroDivisionError
```

## 1 failed 😰

0.22 s ⏱ ``test_failed``

```text
    def test_failed():
>       assert "emoji" == "hello world"
E       AssertionError: assert 'emoji' == 'hello world'
E         - emoji
E         + hello world

test_example1.py:6: AssertionError
```

## 3 passed 😃

### test_example1.py

0.08 s ⏱ ``test_passed[Sara-Hello Sara!]``
0.07 s ⏱ ``test_passed[Mat-Hello Mat!]``
0.08 s ⏱ ``test_passed[Annie-Hello Annie!]``

## 2 skipped 🙄

### test_example1.py

0.00 s ⏱ ``test_skipped``

### test_example2.py

0.00 s ⏱ ``test_skipped``

## 2 xfail 😞

### test_example1.py

0.40 s ⏱ ``test_xfail``

### test_example2.py

0.20 s ⏱ ``test_xfail``

## xpass 😲

### test_example1.py

0.42 s ⏱ ``test_xpass``

### test_example2.py

0.22 s ⏱ ``test_xpass``

**Comment by seanson** [comment]
Sounds good! I've got this format almost up and running.
Did we want the report details to show up or change in any way based on verbosity levels?

**Comment by hackebrot** [comment]
That's a great question. So I would add emojis to the report following the same logic as for the summary. And then with regards to the verbosity level, we could only print the individual results for ``-v`` and above and only print the summary by default.

What do you think @seanson?

**Comment by seanson** [comment]
Sounds good! I've pushed the changes to reflect the same emoji style and added the verbosity toggle. Tests are fixed up as well. Let me know if this is up to standard @hackebrot

**Comment by hackebrot** [comment]
Awesome, great work @seanson! I'll have a look later today. 🚀

**Review by hackebrot — APPROVED** [review]
LGTM @seanson! 👍

**Pull request merged**
